import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Socials from "./components/Socials";
export default function Home() {
  return (
    <div className="px-5 min-h-screen">
      <Head>
        <title>John Barnes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full">
        <div className="py-3 md:py-4">
          <span className="dark:text-yellow-700 md:ml-[6rem]">
            Hi, my name is
          </span>
          <h1 className="py-3 text-6xl  md:text-[10rem] uppercase">
            {" "}
            John Barnes
          </h1>
        </div>
        <div className="grid md:grid-cols-2 gap-3 place-items-center">
          <div className="bg-yellow-500 dark:bg-yellow-700 grid place-items-center h-[250px] md:h-[500px]  w-full rounded-3xl">
            <Image
              src="/barnes.png"
              alt="image"
              width={200}
              height={200}
              className="h-full md:w-[350px]"
            />
          </div>
          <div className="md:-ml-[10rem]">
            <p className="text-3xl  md:text-7xl">
              I&apos;m a fullstack developer in love with programming.
            </p>
            <Link href="mailto:ohenesetwumasi@gmail.com">
              <button className="flex ] rounded-full bg-black text-white px-4 py-2">
                Hire me
              </button>
            </Link>
          </div>
        </div>
        <div className="text-xl md:-mt-[8rem] py-2 flex justify-end">
          <p className="md:w-[400px]  text-xl">
            Here you can learn more about{" "}
            <Link href="/articles" className="underline">
              how I see the web
            </Link>
            , find some of{" "}
            <Link href="/projects" className="underline">
              my projects
            </Link>{" "}
            and information{" "}
            <Link href="/about" className="underline">
              about me.
            </Link>
          </p>
        </div>
      </main>
      <div className="md:my-9 md:py-9 flex justify-center md:justify-end">
        <Socials />
      </div>
    </div>
  );
}
